apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apache-solr
  namespace: cluster-config  # Changed from flux-system
spec:
  interval: 24h
  url: https://solr.apache.org/charts
