apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: staging-solr-search
  namespace: solr-search-staging
spec:
  replicas: 1  # Single replica for staging
  
  # Reduced memory for staging
  solrJavaMem: "-Xms256m -Xmx512m"
  
  # Smaller storage
  storageOptions:
    persistentStorage:
      resources:
        requests:
          storage: "5Gi"
  
  # Reduced resources
  resources:
    requests:
      memory: "768Mi"
      cpu: "150m"
    limits:
      memory: "1Gi"
      cpu: "300m"
  
  zookeeperRef:
    provided:
      zookeeperCluster:
        name: "staging-solr-zookeeper"
        namespace: "solr-search-staging"
  
  # Staging-specific external access
  solrAddressability:
    external:
      method: LoadBalancer
      domainName: "solr-staging.local"
      hideCommon: false
