apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: staging-solr-zookeeper
  namespace: solr-search-staging
spec:
  replicas: 1  # Single replica for staging
  
  persistence:
    spec:
      resources:
        requests:
          storage: 2Gi  # Smaller storage for staging
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"
