# Missing: clusters/aks-cluster/infrastructure.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/aks-cluster/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # This references the AKS-managed GitRepository