apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: production-solr-search
  namespace: solr-search-production
spec:
  replicas: 3  # Full 3-replica cluster for production
  
  # Production memory allocation
  solrJavaMem: "-Xms1g -Xmx2g"
  
  # Production storage
  storageOptions:
    persistentStorage:
      reclaimPolicy: Retain  # Protect production data
      resources:
        requests:
          storage: "20Gi"
  
  # Production resources
  resources:
    requests:
      memory: "2.5Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1000m"
  
  zookeeperRef:
    provided:
      zookeeperCluster:
        name: "production-solr-zookeeper"
        namespace: "solr-search-production"
  
  # Production-specific external access
  solrAddressability:
    external:
      method: LoadBalancer
      domainName: "solr-production.local"
      hideCommon: false
      # Azure LoadBalancer annotations
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-mode: "Auto"
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/solr/admin/info/system"
  
  # Enhanced production configuration
  solrOpts: "-Dsolr.autoSoftCommit.maxTime=5000 -Dsolr.autoCommit.maxTime=30000"
  
  podOptions:
    env:
    - name: SOLR_LOG_LEVEL
      value: "WARN"  # Less verbose logging in production
    - name: GC_TUNE
      value: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=200"
