apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - zookeeper.yaml
  - solrcloud.yaml

commonLabels:
  app.kubernetes.io/name: solr-search
  app.kubernetes.io/part-of: solr-platform
