apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: solr-system
  name: flux-applier-helm
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-helm
  namespace: solr-system
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: solr-system
roleRef:
  kind: Role
  name: flux-applier-helm
  apiGroup: rbac.authorization.k8s.io
