apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: solr-system
  name: flux-applier-helm
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-helm
  namespace: solr-system
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: solr-system
roleRef:
  kind: Role
  name: flux-applier-helm
  apiGroup: rbac.authorization.k8s.io
---
# Comprehensive ClusterRole for Solr and Zookeeper operators
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-applier-cluster-admin
rules:
# CRD management
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Webhook management
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# RBAC management (needed for operators)
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
# Node access (sometimes needed by operators)
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
# Storage classes (for persistent volumes)
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list"]
# Namespace management
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-applier-cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: solr-system
roleRef:
  kind: ClusterRole
  name: flux-applier-cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Role for Zookeeper Operator (namespace-scoped permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: solr-system
  name: zookeeper-operator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["zookeeper.pravega.io"]
  resources: ["zookeeperclusters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zookeeper-operator
  namespace: solr-system
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: solr-system
roleRef:
  kind: Role
  name: zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
