apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: solr-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/crds"
  prune: false  # Don't prune CRDs to avoid accidental deletion
  wait: true
  timeout: 5m
---
# This will be replaced by a directory containing the actual CRDs
# For now, we'll use a Job to fetch and apply them
apiVersion: batch/v1
kind: Job
metadata:
  name: install-solr-crds
  namespace: solr-system
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
spec:
  template:
    spec:
      serviceAccountName: solr-crd-installer
      containers:
      - name: install-crds
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing Solr CRDs..."
          kubectl apply -f https://solr.apache.org/operator/downloads/crds/v0.9.1/all-with-dependencies.yaml
          echo "CRDs installed successfully"
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solr-crd-installer
  namespace: solr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solr-crd-installer
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solr-crd-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: solr-crd-installer
subjects:
- kind: ServiceAccount
  name: solr-crd-installer
  namespace: solr-system
