apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: solr-op
spec:
  interval: 15m
  chart:
    spec:
      chart: solr-operator
      version: "0.9.1"  # ✅ Stable version (not prerelease)
      sourceRef:
        kind: HelmRepository
        name: apache-solr
        namespace: solr-op
      interval: 15m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable ZooKeeper operator as dependency
    zookeeper-operator:
      install: true
    
    # Operator configuration
    image:
      pullPolicy: IfNotPresent
    
    # RBAC configuration
    rbac:
      create: true
    
    # Service account
    serviceAccount:
      create: true
      annotations: {}
    
    # Resource limits for the operator
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Node selector and tolerations if needed
    nodeSelector: {}
    tolerations: []
    affinity: {}