apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: solr-op
spec:
  interval: 15m
  chart:
    spec:
      chart: solr-operator
      version: "0.9.1"  # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: apache-solr
        namespace: solr-op
      interval: 15m
  install:
    createNamespace: false
    crds: Skip  # CRDs managed manually, not by Helm
    remediation:
      retries: 3
  upgrade:
    crds: Skip  # Prevent Helm from managing CRDs on upgrade
    remediation:
      retries: 3
  values:
    # Enable ZooKeeper operator as dependency
    zookeeper-operator:
      install: true
      crd:
        create: false  # Prevent CRD conflicts - CRDs installed manually
    
    # Operator configuration with namespace watching
    image:
      pullPolicy: IfNotPresent
    
    # Environment variables for operator behavior
    env:
      - name: WATCH_NAMESPACES
        value: "solr-op,solr-staging"  # Watch operator namespace + app namespaces
    
    # RBAC configuration
    rbac:
      create: true
    
    # Service account
    serviceAccount:
      create: true
      annotations: {}
    
    # Resource limits for the operator
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Health and metrics configuration
    healthProbeBindAddress: ":8081"
    metricsBindAddress: ":8080"
    
    # Leader election (good for HA)
    leaderElect: true
    
    # Node selector and tolerations if needed
    nodeSelector: {}
    tolerations: []
    affinity: {}
    
    # Security context (recommended)
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    
    # Pod security context
    podSecurityContext:
      fsGroup: 1001