# RBAC for ZooKeeper Operator - Namespace Level
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: solr-op
  name: zookeeper-operator
rules:
# Core resources needed in the namespace
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
# Apps resources
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
# Policy resources
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["*"]
# ZooKeeper CRDs (if any exist in namespace)
- apiGroups: ["zookeeper.pravega.io"]
  resources: ["*"]
  verbs: ["*"]
---
# RoleBinding for namespace-level permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zookeeper-operator
  namespace: solr-op
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: solr-op
roleRef:
  kind: Role
  name: zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole for cluster-wide resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeper-operator-cluster
rules:
# Custom Resource Definitions
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# ZooKeeper CRDs cluster-wide
- apiGroups: ["zookeeper.pravega.io"]
  resources: ["*"]
  verbs: ["*"]
# Node access if needed
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Namespace access
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
# Monitoring
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "create"]
---
# ClusterRoleBinding for cluster-level permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zookeeper-operator-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zookeeper-operator-cluster
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: solr-op