apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: example-solrcloud
spec:
  replicas: 3
  
  # Solr configuration
  solrImage:
    tag: "8.11"
    repository: "solr"
    pullPolicy: "IfNotPresent"
  
  # Java memory settings
  solrJavaMem: "-Xms1g -Xmx2g"
  
  # ZooKeeper configuration
  zookeeperRef:
    provided:
      replicas: 3
      persistence:
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "5Gi"
  
  # Solr storage configuration
  storageOptions:
    persistentVolumeClaimSpec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "10Gi"
  
  # Resource limits for Solr pods
  customSolrKubeOptions:
    podOptions:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2"
      
  # Service configuration
  solrAddressability:
    external:
      method: "Ingress"
      domainName: "solr.local"
      useExternalAddress: false
